package id.anarchy.core;
import com.google.gson.*;import net.kyori.adventure.text.Component;import net.kyori.adventure.text.format.NamedTextColor;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryCloseEvent;import org.bukkit.plugin.java.JavaPlugin;import org.bukkit.scheduler.BukkitTask;import java.io.*;import java.nio.file.*;import java.util.*;
public class AnarchyCore extends JavaPlugin{
 private Storage storage;private Market market;private Bounty bounty;private Combat combat;private Vault vault;private RTP rtp;private DiscordBridge bridge;private Security security;private BukkitTask save;
 public void onEnable(){saveDefaultConfig();storage=new Storage(this);market=new Market(this,storage);bounty=new Bounty(this,storage,market);combat=new Combat(this,bounty);vault=new Vault(this,storage);rtp=new RTP(this,storage);security=new Security(this);getServer().getPluginManager().registerEvents(combat,this);getServer().getPluginManager().registerEvents(market,this);getServer().getPluginManager().registerEvents(security,this);getServer().getPluginManager().registerEvents(new Events(this),this);getServer().getPluginManager().registerEvents(new Listener(){@EventHandler public void close(InventoryCloseEvent e){if(e.getView().title().equals(Component.text("Anarchy Vault",NamedTextColor.DARK_AQUA))&&e.getPlayer() instanceof Player p)vault.save(p,e.getInventory());}},this);combat.start();bridge=new DiscordBridge(this);bridge.start();save=Bukkit.getScheduler().runTaskTimer(this,storage::saveAsync,2400,2400);}
 public void onDisable(){if(bridge!=null)bridge.stop(null);if(combat!=null)combat.stop();if(storage!=null)storage.saveNow();}
 DiscordBridge bridge(){return bridge;} Storage storage(){return storage;}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){String n=c.getName().toLowerCase(Locale.ROOT);if(n.equals("balance")&&s instanceof Player p){market.balance(p);return true;}if(n.equals("pay")&&s instanceof Player p){market.pay(p,a);return true;}if(n.equals("sell")&&s instanceof Player p){market.sell(p,a);return true;}if(n.equals("baltop")){market.baltop(s);return true;}if(n.equals("eco")){market.eco(s,a);return true;}if(n.equals("bounty")){bounty.command(s,a);return true;}if(n.equals("rtp")&&s instanceof Player p){rtp.rtp(p);return true;}if(n.equals("vault")&&s instanceof Player p){vault.open(p);return true;}if(n.equals("market")){market.info(s,a);return true;}if(n.equals("stats")){stats(s,a);return true;}if(n.equals("top")){top(s);return true;}if(n.equals("anarchycore")&&a.length>0&&a[0].equalsIgnoreCase("reload")){reloadConfig();market.reload();combat.reload();s.sendMessage(Component.text("AnarchyCore reloaded.",NamedTextColor.GREEN));return true;}return true;}
 private void stats(CommandSender s,String[]a){Player p=a.length>0?Bukkit.getPlayerExact(a[0]):s instanceof Player x?x:null;if(p==null){s.sendMessage(Component.text("Player tidak online.",NamedTextColor.RED));return;}int k=p.getStatistic(Statistic.PLAYER_KILLS),d=p.getStatistic(Statistic.DEATHS),t=p.getStatistic(Statistic.PLAY_ONE_MINUTE);double kd=d==0?k:k/(double)d;s.sendMessage(Component.text("== "+p.getName()+" ==",NamedTextColor.GOLD));s.sendMessage(Component.text("Kills: "+k+" | Deaths: "+d+" | K/D: "+String.format(Locale.ROOT,"%.2f",kd),NamedTextColor.YELLOW));s.sendMessage(Component.text("Playtime: "+t/72000+"h | Balance: "+market.fmt(storage.money.getOrDefault(p.getUniqueId(),0L))+" | Bounty: "+market.fmt(bounty.of(p.getUniqueId())),NamedTextColor.YELLOW));}
 private void top(CommandSender s){List<Player>ps=new ArrayList<>(Bukkit.getOnlinePlayers());ps.sort((a,b)->Integer.compare(b.getStatistic(Statistic.PLAYER_KILLS),a.getStatistic(Statistic.PLAYER_KILLS)));s.sendMessage(Component.text("== TOP ONLINE KILLS ==",NamedTextColor.GOLD));for(int i=0;i<Math.min(10,ps.size());i++)s.sendMessage(Component.text((i+1)+". "+ps.get(i).getName()+" "+ps.get(i).getStatistic(Statistic.PLAYER_KILLS),NamedTextColor.YELLOW));}
}