package id.anarchy.core;
import net.kyori.adventure.text.Component;import net.kyori.adventure.text.format.NamedTextColor;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public class Bounty{
 private final AnarchyCore p;private final Storage s;private final Market m;private final Map<String,Long> recent=new HashMap<>();
 Bounty(AnarchyCore p,Storage s,Market m){this.p=p;this.s=s;this.m=m;}long of(UUID u){return u==null?0:s.bounty.getOrDefault(u,0L);}private void set(UUID u,long v){if(v<=0)s.bounty.remove(u);else s.bounty.put(u,v);s.dirty();}private String n(UUID u){String x=Bukkit.getOfflinePlayer(u).getName();return x==null?"?":x;}
 void onKill(UUID k,UUID v){if(k==null||k.equals(v)||!p.getConfig().getBoolean("bounty.enabled",true))return;long now=System.currentTimeMillis();String key=k+":"+v;long cd=p.getConfig().getLong("bounty.same-victim-cooldown-minutes",5)*60000;Long old=recent.get(key);if(old!=null&&now-old<cd)return;recent.put(key,now);long vb=of(v),pct=Math.max(0,Math.min(1,p.getConfig().getDouble("bounty.claim-percent",.65))),reward=Math.round(vb*pct);if(reward>0){set(v,vb-reward);s.money.merge(k,reward,Long::sum);Bukkit.broadcast(Component.text(n(k)+" claimed "+m.fmt(reward)+" bounty from "+n(v)+"!",NamedTextColor.GOLD));}long add=Math.round(p.getConfig().getDouble("bounty.per-kill",500)*100),max=Math.round(p.getConfig().getDouble("bounty.max",1000000)*100);set(k,Math.min(max,of(k)+add));}
 void combatLog(UUID k,UUID v){if(k!=null)onKill(k,v);}
 void command(CommandSender s,String[] a){if(a.length==0){if(s instanceof Player x)msg(x,"Your bounty: "+m.fmt(of(x.getUniqueId())),NamedTextColor.GOLD);return;}if(a[0].equalsIgnoreCase("top")){top(s);return;}if(a[0].equalsIgnoreCase("add")){add(s,a);return;}OfflinePlayer t=Bukkit.getOfflinePlayerIfCached(a[0]);if(t==null){msg(s,"Player not found.",NamedTextColor.RED);return;}msg(s,t.getName()+" bounty: "+m.fmt(of(t.getUniqueId())),NamedTextColor.GOLD);}
 private void top(CommandSender s){List<Map.Entry<UUID,Long>>x=new ArrayList<>(this.s.bounty.entrySet());x.sort((a,b)->Long.compare(b.getValue(),a.getValue()));msg(s,"== BOUNTY TOP 10 ==",NamedTextColor.GOLD);for(int i=0;i<Math.min(10,x.size());i++)msg(s,(i+1)+". "+n(x.get(i).getKey())+" "+m.fmt(x.get(i).getValue()),NamedTextColor.YELLOW);}
 private void add(CommandSender z,String[]a){if(!(z instanceof Player p1)||a.length<3){msg(z,"/bounty add <player> <amount>",NamedTextColor.RED);return;}OfflinePlayer t=Bukkit.getOfflinePlayerIfCached(a[1]);if(t==null||t.getUniqueId().equals(p1.getUniqueId())){msg(p1,"Target invalid.",NamedTextColor.RED);return;}double d;try{d=Double.parseDouble(a[2]);}catch(Exception e){msg(p1,"Invalid amount.",NamedTextColor.RED);return;}long c=Math.round(d*100),bal=s.money.getOrDefault(p1.getUniqueId(),0L),max=Math.round(p.getConfig().getDouble("bounty.max",1e6)*100);if(c<=0||c>bal||of(t.getUniqueId())+c>max){msg(p1,"Invalid amount, balance, or bounty cap.",NamedTextColor.RED);return;}s.money.put(p1.getUniqueId(),bal-c);set(t.getUniqueId(),of(t.getUniqueId())+c);Bukkit.broadcast(Component.text(p1.getName()+" placed "+m.fmt(c)+" bounty on "+t.getName()+".",NamedTextColor.GOLD));}
 private void msg(CommandSender s,String x,NamedTextColor c){s.sendMessage(Component.text(x,c));}
}