package id.anarchy.core;
import net.kyori.adventure.text.Component;import net.kyori.adventure.text.format.NamedTextColor;import org.bukkit.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.scheduler.BukkitTask;import java.util.*;
public class Combat implements Listener{
 private static final String BYPASS="anarchycore.combat.bypass";private final AnarchyCore p;private final Bounty b;private final Map<UUID,Long>tag=new HashMap<>();private final Map<UUID,UUID> attacker=new HashMap<>();private final Set<String> blocked=new HashSet<>();private BukkitTask task;
 Combat(AnarchyCore p,Bounty b){this.p=p;this.b=b;reload();}void reload(){var c=p.getConfig();blocked.clear();for(String x:c.getStringList("combat.blocked-commands"))blocked.add(x.toLowerCase(Locale.ROOT).replace("/",""));}void start(){task=Bukkit.getScheduler().runTaskTimer(p,this::tick,10,10);}void stop(){if(task!=null)task.cancel();tag.clear();attacker.clear();}boolean in(Player x){return tag.getOrDefault(x.getUniqueId(),0L)>System.currentTimeMillis();}private void tag(Player a,Player v){long t=System.currentTimeMillis()+p.getConfig().getLong("combat.seconds",25)*1000;tag.put(a.getUniqueId(),t);attacker.put(a.getUniqueId(),v.getUniqueId());}
 private void tick(){long n=System.currentTimeMillis();for(Iterator<Map.Entry<UUID,Long>>i=tag.entrySet().iterator();i.hasNext();){var e=i.next();Player x=Bukkit.getPlayer(e.getKey());if(x==null){i.remove();continue;}long left=e.getValue()-n;if(left<=0){i.remove();attacker.remove(e.getKey());x.sendActionBar(Component.text("Combat selesai.",NamedTextColor.GREEN));}else x.sendActionBar(Component.text("⚔ COMBAT "+((left+999)/1000)+"s",NamedTextColor.RED));}}
 private Player atk(Entity e){if(e instanceof Player x)return x;if(e instanceof Projectile q&&q.getShooter() instanceof Player x)return x;return null;}
 @EventHandler(ignoreCancelled=true,priority=EventPriority.MONITOR)public void hit(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof Player v))return;Player a=atk(e.getDamager());if(a==null||a.equals(v)||a.hasPermission(BYPASS)||v.hasPermission(BYPASS))return;tag(a,v);tag(v,a);}
 @EventHandler(ignoreCancelled=true)public void cmd(PlayerCommandPreprocessEvent e){if(!in(e.getPlayer()))return;String c=e.getMessage().substring(1).split(" ",2)[0].toLowerCase(Locale.ROOT);if(blocked.contains(c)||c.contains(":")&&blocked.contains(c.substring(c.indexOf(':')+1))){e.setCancelled(true);e.getPlayer().sendMessage(Component.text("Tidak bisa saat combat.",NamedTextColor.RED));}}
 @EventHandler(ignoreCancelled=true)public void quit(PlayerQuitEvent e){Player x=e.getPlayer();if(!in(x)||Bukkit.isStopping()||x.hasPermission(BYPASS))return;UUID k=attacker.get(x.getUniqueId());tag.remove(x.getUniqueId());attacker.remove(x.getUniqueId());p.getServer().broadcast(Component.text(x.getName()+" combat-logged.",NamedTextColor.RED));if(p.getConfig().getBoolean("combat.punish-logout",true)){b.combatLog(k,x.getUniqueId());}}
 @EventHandler public void death(PlayerDeathEvent e){if(in(e.getEntity()))tag.remove(e.getEntity().getUniqueId());b.onKill(e.getEntity().getKiller()==null?null:e.getEntity().getKiller().getUniqueId(),e.getEntity().getUniqueId());}
 @EventHandler(ignoreCancelled=true)public void glide(EntityToggleGlideEvent e){if(e.getEntity() instanceof Player x&&e.isGliding()&&in(x)&&p.getConfig().getBoolean("combat.disable-elytra",true))e.setCancelled(true);}
}